### ISSUE TITLE
Big Map Processing Not Working (Maybe map Lua?)

### ISSUE THREAD

**Issue by IIPoliII** [L0laapk3/FactorioMaps#24] opened 2019-02-21 14:43 UTC
Hello,
I am trying to create a FactorioMaps preview for this actual map : https://factorio-saves.poli.fun/Home/Join-And-Play-Coop-Saves/Old-Saves/06-Feb-12:54.zip

Sadly i the map don't get corped i except 2 things : 
- The Map has blank spaces between discorvered one (everything is not bounded)
- The Lua's script in the map make some problems

Is there any fix for maps like this maybe could you try to fix it by your side ?
Thanks Poli ^^

**Comment by L0laapk3** [comment] 2019-02-21 14:49
If you want to increase the screenshotting range  have a look at some of the configuration settings: https://github.com/L0laapk3/FactorioMaps/blob/master/README.md

What problems are you experiencing with the "script in the map"? (I assume you are talking about a scenario script?)

**Comment by IIPoliII** [comment] 2019-02-21 14:55
Okay i will try for the first one. But yes i mean Scenario because when i ran the "script" at first it did me an error with lua. And never starts the process of making the screenshots. https://i.imgur.com/JrlCnx1.png

**Comment by L0laapk3** [comment] 2019-02-21 15:06
Thats a false error, its a problem with factorio that will be fixed in 0.17. See #15.

If you've interrupted the script before or it had an error, its quite likely that the output folder for that map is in a bricked state and you should `--delete` it.

If thats not the cause of the problem, one of the things you can try is: if you are running a lot of mods, it might be useful to figure out why things are not working to use the `--verbosegame` flag. Can you also let me know whats happening to factorio in the meantime, if it gets stuck somewhere?

**Comment by IIPoliII** [comment] 2019-02-21 15:28
I will try this once I get home again in a few hours thanks !

**Comment by IIPoliII** [comment] 2019-02-21 18:15
Okay i try now but i tried again normally on another PC and got this error like a permission error from factorio so it don't move now. https://i.imgur.com/LK0qOqW.png Same with other maps who worked on python 2. But this time is probably an permission error
(god)

**Comment by IIPoliII** [comment] 2019-02-21 18:18
The folder seem to have the good permissions it's weird

**Comment by L0laapk3** [comment] 2019-02-21 18:21
Can you try deleting the output folder (script-output/JAPC-Feb-06) before running? its likely that a previous crash caused the folder to be in some kind of bricked state now.

**Comment by IIPoliII** [comment] 2019-02-21 18:23
yes sure

**Comment by IIPoliII** [comment] 2019-02-21 18:26
Well the error is still there it's weird that i don't accept to save their i will try to execute it as admin
but it should work

**Comment by IIPoliII** [comment] 2019-02-21 18:32
what i found really weird is that he actually is able to create the folders and create them except the script-output one.

**Comment by L0laapk3** [comment] 2019-02-21 18:37
it could also be that your drive is full or something. Also, in this (https://i.imgur.com/rMoj2PO.png) screenshot you are using a different output folder, just to be sure did you try deleting that one before it starts?

**Comment by IIPoliII** [comment] 2019-02-21 18:41
Yes but it's the pc's problem i guess i tried again on my laptop all is good. But on the other pc i removed the folders on both outputs but is probably an system error can not be your fault. But i am trying the script again on my laptop for now it's working but i guess it can take up all the night because of the size of the map let's check!

**Comment by IIPoliII** [comment] 2019-02-21 19:47
Well big maps seems like it can't be processed even with new settings :/ it stays stuck

**Comment by L0laapk3** [comment] 2019-02-21 20:16
Can you upload the map + zip of mods if any? I'll try it myself then

>

**Comment by IIPoliII** [comment] 2019-02-21 21:44
Sure here is the zip https://factorio-saves.poli.fun/Home/Join-And-Play-Coop-Saves/Old-Saves/06-Feb-12:54.zip

**Comment by IIPoliII** [comment] 2019-02-21 21:44
Thanks for your help between!

**Comment by L0laapk3** [comment] 2019-02-23 12:40
I've noticed that your maps just takes ages before it starts doing anything, I've found one bug that gave an error but I haven't seen you report it, other than that it just takes a long time before it starts doing anything, presumably because of the size of  the map.

**Comment by IIPoliII** [comment] 2019-02-23 13:04
> 
> 
> I've noticed that your maps just takes ages before it starts doing anything, I've found one bug that gave an error but I haven't seen you report it, other than that it just takes a long time before it starts doing anything, presumably because of the size of the map.

Oh really? What bug for me i have not any errors on this map. But i am intressted what is it?

**Comment by L0laapk3** [comment] 2019-02-23 23:42
I got that after about 8 minutes of waiting, but don't worry about it too much as I fixed the bug already. I'm now able to generate timelines of your savefile. :D

**Comment by IIPoliII** [comment] 2019-02-24 00:01
Oh damn how did you did the timelines?

**Comment by L0laapk3** [comment] 2019-02-24 00:15
I just mixed it with a completely different savefile from me lol

**Comment by IIPoliII** [comment] 2019-02-24 10:33
Yes it works but sadly on my main pc I got a tiny main ssd do you know if there is an option to change the default temp folder since the map generates me more than 50gb of Printscreen at first ? Thanks ^^

**Comment by L0laapk3** [comment] 2019-02-24 12:07
The temp folder doesnt actually store any significant amount of data. What you can do (what I did) is create a symlink from script-output/FactorioMaps to for example D:/FactorioMaps: on windows this would be (from cmd from in the script-output folder) `MKLINK /J FactorioMaps D:/FactorioMaps`

**Comment by IIPoliII** [comment] 2019-02-24 12:14
Yes I know what you mean but actually I think the symlink don't work as excepted. Factorio actually write at first in the temp folder and it's not really symlinked the error happens at a moment sadly I didn't made a print screen I remember it was an issue https://forums.factorio.com/viewtopic.php?t=6397 for crashes I guess they fixed it by finishing the current-game and then one it's finished move it to the actual script-output folder

**Comment by L0laapk3** [comment] 2019-02-25 11:13
If factorio makes the screenshots to a temp folder before moving them, there shouldnt be more than a handfull of screenshots there at once anyways. Either way, I dont have any idea how to work around that then. Sorry.

**Comment by L0laapk3** [comment] 2019-02-25 16:28
Feel free to reopen or create a new issue if you think there are still bugs.

**Closed** 2019-02-25 16:28 UTC
Labels: bug, help wanted
