### ISSUE TITLE
Script just freezes after generating images (100+ hour game Space Exploration + Krastorio)

### ISSUE THREAD

**Issue by DrParanoia** [L0laapk3/FactorioMaps#110] opened 2022-10-03 12:24 UTC
So, at some point in my save file the script simply stops after killing Factorio (no error messages, no progress, no nothing).

Tried running it on a virtual Linux machine, it seems that the script does indeed continue past the point it freezes on Windows, but in the end there is some kind of different error which prevents final metadata files to be generated.

Maybe there could be an option to skip the screenshot generation and move to the last part where the metadata is generated? Thanks!

Platform: Windows 11
RAM: 32GB
Processor: Ryzen 5800x

**Comment by MysticMia** [comment] 2022-12-07 20:38
You might be running into this:
KeyError: "There is no item named 'space-exploration-graphics_0.6.13/graphics/icons/alerts/core-seam-icon.png' in the archive" on line 804, "zipInfo = zipObj.getinfo(os.path.join(mod[2], icon + ".png").replace('\\', '/'))"
Cause I probably have exactly the same issue. I checked in the zip folders. The image file exists and follows nearly the same path. Only the version section of the mod folder seemed different inside the zip file:
In zip file: space-exploration-graphics/graphics/icons/alerts/core-seam-icon.png
Program: space-exploration-graphics_0.6.13/graphics/icons/alerts/core-seam-icon.png

I checked other issues. It seems linked to #99

**Comment by DrParanoia** [comment] 2022-12-16 17:22
@MysticMia Don't think so. It was working fine up until about like 160h mark 😄 Also there are absolutely no errors. I remember having the error you described, and I think I solved it by downloading the mod directly from the `dev` branch here.

**Comment by L0laapk3** [comment] 2022-12-24 16:37
Sorry for the lack of responses. Were you able to reproduce the crash multiple times or is this a random thing?

As for "the option to skip screeshot generation", there is already something like that `--dry`, however I can't recommend using it.

The linux problem may be caused by https://github.com/L0laapk3/FactorioMaps/issues/102 .

**Comment by DrParanoia** [comment] 2022-12-25 18:03
@L0laapk3 Well it's not a crash :( It just sits there with no messages and no CPU use. Will the `--dry` option continue the processing though after skipping the screenshot part? I think I've tried it, and it did not.

**Comment by L0laapk3** [comment] 2022-12-25 18:13
If this is something that is happening consistently, it might be worth it for me to try to run it for your savefile & mods folder.

**Comment by DrParanoia** [comment] 2022-12-26 08:08
Sure, I tried to find the smallest save out of my backups because otherwise it will take A LOOONG TIME for you to test 😆 https://drive.google.com/file/d/1bybJIJR7e7ivYuK3zsOOdxXv6eMAlIp-/view?usp=share_link

Please note, that it's happening on Windows. Thanks!

**Comment by L0laapk3** [comment] 2023-10-13 15:15
Hey, I tried running this on the latest dev branch on a fresh windows install and it worked without hiccups.
I'm going to close this, if there are any further problems feel free to open a new issue :)

**Closed by L0laapk3** 2023-10-13 15:15 UTC
Labels: needs-more-info
