### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by skairunner** [L0laapk3/FactorioMaps#89] opened 2020-10-10 23:19 UTC
Using this save file and running `python auto.py` with no arguments, the conversion process stalls on this step: 

![image](https://user-images.githubusercontent.com/3517115/95666971-bb790000-0b5f-11eb-900b-1db47ee8bc1e.png)

Is this a hang or is it just taking a while to process? It worked on a previous version of the save.
[neerskai v2.zip](https://github.com/L0laapk3/FactorioMaps/files/5360405/neerskai.v2.zip)

**Comment by L0laapk3** [comment] 2020-10-11 09:00
Thats strange. Can you run with --verbose and kill it (ctrl + c) to see where exactly it hangs?

**Comment by skairunner** [comment] 2020-10-11 10:57
This is the log.
[factoriomapslog.txt](https://github.com/L0laapk3/FactorioMaps/files/5360955/factoriomapslog.txt)

It's certainly getting interrupted in the middle of parallel code, but I don't think that's saying much :P There's also a whole host of "unidentified image error"s that interrupt the progress bar.

**Comment by L0laapk3** [comment] 2020-10-11 15:24
Is it possible your storage is temporarily full while it is running? It seems like factorio is struggling saving the images. --verbosegame will likely reveal why

**Comment by skairunner** [comment] 2020-10-11 18:46
It seems to work fine when --verbosegame is enabled. I have to say that it has got to be some kind of race condition or deadlock.

**Comment by L0laapk3** [comment] 2020-10-11 19:12
You're positive that it can't have been a storage space issue? Since it
seems like therr were a ton of images that factorio failed to save.

**Comment by skairunner** [comment] 2020-10-11 19:20
I have 32 GB ram and 1 TB ssd, of which 800GB is free, and I've only played
9 hours on the save. I dont think it's storage issues?

**Comment by L0laapk3** [comment] 2020-10-11 19:22
Okay sounds fair, I just wanted to make sure :p strange that it failed,
there might indeed be some weird race condition somewhere.

**Comment by skairunner** [comment] 2020-10-11 19:25
I also have 16 processors, maybe I could try re-running with just 1...

**Comment by L0laapk3** [comment] 2020-10-17 23:02
Did you end up resolving this? Weird. I've had one or two similar issues made by people in the past, but I've never been able to reproduce it.

**Comment by skairunner** [comment] 2020-10-17 23:31
Unfortunately I just gave up on using factorio maps instead :(

**Comment by L0laapk3** [comment] 2020-10-18 00:21
Thats unfortunate.
I've tried running it on your savefile just now and it worked for me.
I've had another look at your logs, and they indicate that it was ran on an already existing timeline. This means my test conditions are not the same as yours.
Just to be clear, if factoriomaps has already crashed or hung once, chances are the timeline ended up in a "bricked" state and factoriomaps couldn't build further on it anymore. While its possible to manually correct this, its usually simpler to just delete the respective output folder inside script-output and run the script again.

If you decide to give it another go, feel free to contact me. :P

**Comment by skairunner** [comment] 2020-10-18 09:28
What I would most like is some way to combine timelines from multiple
files. I have backups saved for my main game under different names, and the
script usually works for a fresh save, so if I could combine them...

**Comment by L0laapk3** [comment] 2020-10-18 11:12
Its not entirely clear to me what your intention is. Its possible to append savefiles to timelines already

**Comment by L0laapk3** [comment] 2020-12-13 23:47
Closing. feel free to reopen

**Closed by L0laapk3** 2020-12-13 23:47 UTC
