### ISSUE TITLE
Error while starting the mod

### ISSUE THREAD

**Issue by Luke-101** [L0laapk3/FactorioMaps#49] opened 2019-09-27 16:13 UTC
Hello, so I have tried to install this mod to factorio but every time I tried to open it, it give me this error.
![image](https://user-images.githubusercontent.com/53636779/65784353-22dd3100-e152-11e9-84c5-6024bc555594.png)
I also tried to modify the files but I'm not a expert on lua or python so there wasn't much I could do to discover the cause of this error. I also tried to install 3 times the mod, to specify the save file path, the facorio path and I tried to start factorio with only this mod on the mods folder but nothing will work.
Any idea on how to fix this bug ?

**Comment by Luke-101** [comment] 2019-09-27 16:20
Also this is the log when I close factorio after the error:
<details>
  <summary>LOG</summary>
  C:\Users\Luke\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_3.5.0>python auto.py
No save name passed. Using most recent save: test
factorio path: C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe
output folder: script-output\FactorioMaps\test
checking for updates
enabling FactorioMaps mod
cleaning up
building autorun.lua
building config.ini
starting factorio
WARNING: Running in limited support mode trough steam. Consider using standalone factorio instead.
         If you have any default arguments set in steam for factorio, delete them and restart the script.
         Please alt tab to steam and confirm the steam 'start game with arguments' popup.
         (Yes, you'll have to click this every time the game starts for the steam version)
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\_pswindows.py", line 716, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\_pswindows.py", line 935, in create_time
    return cext.proc_create_time(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 473, in _init
    self.create_time()
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 823, in create_time
    self._create_time = self._proc.create_time()
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\_pswindows.py", line 718, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=5572)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Luke\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_3.5.0\auto.py", line 185, in startGameAndReadGameLogs
    psutil.Process(pid).nice(psutil.BELOW_NORMAL_PRIORITY_CLASS if os.name == 'nt' else 10)
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 446, in __init__
    self._init(pid)
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 486, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 5572
</details>
<details>
  <summary>Image</summary>
![image](https://user-images.githubusercontent.com/53636779/65784905-7e5bee80-e153-11e9-850f-0480cb59168a.png)

</details>

**Comment by L0laapk3** [comment] 2019-09-28 09:02
I'll have a look at it. Can you include your mods?

**Comment by Luke-101** [comment] 2019-09-28 09:04
It didn't work with any mods, but if you want I can give you the mods I use frequently

**Comment by L0laapk3** [comment] 2019-09-28 09:13
If it crashes without any other mods, I don't need any mods.

Is it crashing when you boot up the game, or when you're loading a save
file? In the last case can you attach the save file?

**Comment by Luke-101** [comment] 2019-09-28 10:37
Sorry for the late reply.
When I launch the game, it loads verything but then it gives me this error.
the test save that you see in the log is a new world without any building.
If you want there it is:  [test.zip](https://github.com/L0laapk3/FactorioMaps/files/3665346/test.zip)

**Comment by L0laapk3** [comment] 2019-09-29 16:26
Unfortunately my laptop is kind of broken so I don't really have the means to check it out right now, but this sounds extremely weird, unless a factorio update broke something significant, not being able to load the game at all with no other mods at all makes me very confused and I would have definitely caught that or someone else would have. I will check it out when I can but it might take me some time.

**Comment by Luke-101** [comment] 2019-09-29 19:00
ok sure, take your time. 
In the meanwhile I will test some other things because it's also the only mod to give me this error, that's the real strange thing

**Comment by Luke-101** [comment] 2019-10-01 12:05
I just tested 2 other maps, created one when the mod was one and the other when it was off, and they gave me the same error (1° post) when I tried to opened them.

**Comment by L0laapk3** [comment] 2019-10-08 14:16
I've tried to reproduce your error, but it just works normally for me without mods. The error from your screenshot does hint that there are some other mods causing some issues, are you sure that the error occurs with no other mods enabled?

**Comment by Luke-101** [comment] 2019-10-08 14:38
yes I'm sure.
Just to be clear: to start with a new save file, you have to open factorio normaly, save and then open factorio with cmd auto.py (with the other istance of factorio closed), right ?
Also the path for the mods is: C:\Users\Luke\AppData\Roaming\Factorio\mods, right ?

**Comment by L0laapk3** [comment] 2019-10-08 16:44
as long as the savefile exists you should be able to run the python auto.py command yea, you dont need to be running anything else.

Can you run it with `--verbosegame` as flag and see what it spits out?

**Comment by Luke-101** [comment] 2019-10-08 18:10
`C:\Users\Luke\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_3.5.0>python auto.py --verbosegame
No save name passed. Using most recent save: test3
factorio path: C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe
output folder: script-output\FactorioMaps\test3
checking for updates
enabling FactorioMaps mod
cleaning up
building autorun.lua
building config.ini
starting factorio
[GAME]    0.000 Initializing Steam API.
WARNING: Running in limited support mode trough steam. Consider using standalone factorio instead.
         If you have any default arguments set in steam for factorio, delete them and restart the script.
         Please alt tab to steam and confirm the steam 'start game with arguments' popup.
         (Yes, you'll have to click this every time the game starts for the steam version)
[GAME]    0.001 2019-10-08 20:09:11; Factorio 0.17.68 (build 47074, win64, steam)
[GAME]    0.001 Operating system: Windows 10 (version 1809)
[GAME]    0.001 Program arguments: "C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe" "--load-game" "C:\Users\Luke\AppData\Roaming\Factorio\saves\test3.zip" "--disable-audio" "--config" "C:\Users\Luke\AppData\Local\Temp\FactorioMaps-750382279\config/config.ini" "--mod-directory" "C:\Users\Luke\AppData\Roaming\Factorio\mods" "--disable-migration-window"
[GAME]    0.001 Read data path: C:/Program Files (x86)/Steam/steamapps/common/Factorio/data
[GAME]    0.001 Write data path: C:/Users/Luke/AppData/Local/Temp/FactorioMaps-750382279 [84647/242934MB]
[GAME]    0.002 Binaries path: C:/Program Files (x86)/Steam/steamapps/common/Factorio/bin
[GAME]    0.027 System info: [CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx, 8 cores, RAM: 5543/10153 MB, page: 8803/11689 MB, virtual: 4273/134217727 MB, extended virtual: 0 MB]
[GAME]    0.027 Display options: [FullScreen: 1] [VSync: 1] [UIScale: custom (100.0%)] [Native DPI: 1] [Screen: 255] [Special: 0000] [Lang: en]
[GAME]    0.035 Available displays: 1
[GAME]    0.035  [0]: \\.\DISPLAY1 - AMD Radeon(TM) Vega 8 Graphics {0x80005, [0,0], 1920x1080, 32bit, 60Hz}
[GAME]    0.083 [Direct3D11] Display: 0, Output: 0, DisplayAdapter: 0, RenderingAdapter: 0; d3dcompiler_47.dll
[GAME]    0.145 Initialised Direct3D[0]: AMD Radeon(TM) Vega 8 Graphics; id: 1002-15d8; driver: aticfx64.dll 26.20.11002.12
[GAME]    0.145   D3D Feature Level: 11.1, DXGI 1.5+, SwapChain: 3,flip-discard,-,-,-,none
[GAME]    0.145   [Local Video Memory] Budget: 6398MB, CurrentUsage: 0MB, Reservation: 0/3377MB
[GAME]    0.145   [Non-Local Vid.Mem.] Budget: 0MB, CurrentUsage: 0MB, Reservation: 0/0MB
[GAME]    0.145   Tiled resources: Tier 2
[GAME]    0.145   Unified Memory Architecture: Yes
[GAME]    0.145   BGR 565 Supported: Yes
[GAME]    0.145   MaximumFrameLatency: 3, GPUThreadPriority: 0
[GAME]    0.146 Graphics settings preset: integrated-gpuhigh
[GAME]    0.146   Dedicated video memory size 2032 MB
[GAME]    0.221 Desktop composition is active.
[GAME]    0.221 Graphics options: [Graphics quality: high] [Video memory usage: all] [Light scale: 100%] [DXT: low-quality]
[GAME]    0.221                   [Max load threads: 32] [Max texture size: 0] [Tex.Stream.: 0] [Rotation quality: low] [Color: 32bit]
[GAME]    0.221 Audio is disabled
[GAME]    0.447 Loading mod core 0.0.0 (data.lua)
[GAME]    0.747 Loading mod base 0.17.68 (data.lua)
[GAME]    1.766 Loading mod base 0.17.68 (data-updates.lua)
[GAME]    1.945 Loading mod L0laapk3_FactorioMaps 3.5.0 (data-final-fixes.lua)
[GAME]    1.961 Error ModManager.cpp:1323: Failed to load mod "L0laapk3_FactorioMaps": Flush failed: Invalid argument
stack traceback:
        [C]: in function 'log'                                                                                          
        __L0laapk3_FactorioMaps__/data-final-fixes.lua:46: in function 'index'                                          
        __L0laapk3_FactorioMaps__/data-final-fixes.lua:53: in main chunk                                                
[GAME]    1.964 Loading mod core 0.0.0 (data.lua)
[GAME]    2.100 Checksum for core: 3551490305
[GAME]    2.311 Error ModManager.cpp:1323: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
[GAME]    2.336 Crop bitmaps.
[GAME]    2.364 Parallel Sprite Loader initialized (threads: 7)
[GAME]    2.404 Initial atlas bitmap size is 16384
[GAME]    2.405 Created atlas bitmap 2048x416 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
[GAME]    2.417 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
[GAME]    2.444 Parallel Sprite Loader initialized (threads: 7)
[GAME]    2.532 Sprites loaded
[GAME]    2.546 Generated mipmaps (5) for atlas [0] of size 2048x416
[GAME]    2.546 Custom mipmaps uploaded.
[GAME]    2.558 Factorio initialised
[GAME]    2.569 Mods to disable:Failed to load mods: Flush failed: Invalid argument
stack traceback:
        [C]: in function 'log'                                                                                          
        __L0laapk3_FactorioMaps__/data-final-fixes.lua:46: in function 'index'                                          
        __L0laapk3_FactorioMaps__/data-final-fixes.lua:53: in main chunk                                                

Mods to be disabled:
â€¢ L0laapk3_FactorioMaps`

**Comment by L0laapk3** [comment] 2019-10-08 20:04
this makes very little sense to me. I assume you also haven't messed with the base games files since you did a reinstall.

Can you post the log after you replace the data-final-fixes.lua file of factoriomaps with this one? https://transfer.sh/YU7sh/data-final-fixes.lua  
I've added some extra logs.

**Comment by OvermindDL1** [comment] 2019-10-08 20:06
```
[GAME] 2.311 Error ModManager.cpp:1323: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
```
Uh, what?  This seems really odd...  Is your factorio installation corrupt?

**Comment by Luke-101** [comment] 2019-10-08 21:01
So when I read again the log I noticed that I was on 0.17.68 and not the latest 0.17.69.
So I forced the update from steam and then I redone the test and to my surprase there wasn't any error message but when the world was fully loaded the game crashed.
This are the logs (verbose was very long this time so I put theme in files)(Multiple logs because the errors were different every time):
[log.txt](https://github.com/L0laapk3/FactorioMaps/files/3704460/log.txt)
[log2.txt](https://github.com/L0laapk3/FactorioMaps/files/3704487/log2.txt)

So I think OvermindDL1 was right and my factorio was corrupt but not so much to crash when I played without this mod, very strange.

P.S. the last percentage can very from 0.3% to 100% (as in the log)

**Comment by OvermindDL1** [comment] 2019-10-08 21:08
> log.txt

For the first log there is `[GAME]   22.663 Quitting: window closed.`, which means that it looks like you closed the game manually instead of letting the script run (it can take a bit) and let it close it itself.

> log2.txt
The second one also says `[GAME]   21.609 Quitting: window closed.` thus the same thing there.  You need to leave the window up and running.

**Comment by L0laapk3** [comment] 2019-10-08 21:14
Nice that the original issue got resolved.

Further, theres a possibility previous attempts at this mod are causing the current attempts to also crash, can you `--delete` the script-output/factoriomaps/savename folder of the map youre trying to generate? Let me know if that fixes things.

**Comment by Luke-101** [comment] 2019-10-08 21:21
I tried to delete the folder manually and then with the argument but it instant crash after the sub hotbar (the copy, paste, delete one) disappeared, and my fps were below 10

**Comment by L0laapk3** [comment] 2019-10-08 22:39
Sorry, what? I think you're confusing multiple things. When factoriomaps
takes control, it completely freezes your game and then exits it, at no
point can it cause bad fps. Did the map generate successfully?

>

>

**Comment by Luke-101** [comment] 2019-10-09 05:33
Well I think because the game just started when the crash appens probably It doesn't have any time to update that label.
I was only writing down everything I saw.
Just to be sure, can you give me a save to test ?

**Comment by L0laapk3** [comment] 2019-10-09 08:52
It should be able to generate a map of any save. Note that in the savefile you uploaded earlier, factoriomaps had already ran, you should not be saving after factoriomaps runs.

Can you describe the problem you're having from start? In the logs you posted, the first one seemed to just be caused by an artifact from previous failed runs and the second one seems to have been ended prematurely from what I can tell.

**Comment by Luke-101** [comment] 2019-10-09 09:35
So this was my process:

1. started factorio normally

**Comment by OvermindDL1** [comment] 2019-10-09 14:05
`[GAME]   29.852 Quitting: window closed.` Still makes me curious.  It's not being manually closed?  Or is that just what windows does when it receives a kill signal (where at least for me it says it received a kill signal and is dying)?

**Comment by Luke-101** [comment] 2019-10-09 16:27
Because there is a little confiusion on what happens I made a video:
[video](https://github.com/L0laapk3/FactorioMaps/files/3708433/2019-10-09.18-21-44.zip)

**Comment by OvermindDL1** [comment] 2019-10-09 16:57
Any chance at using the current `dev` branch of this mod?  The L0laapk3 added some debugging things recently that might help.  If you aren't using `git` you can download a copy of it at https://github.com/L0laapk3/FactorioMaps/archive/dev.zip and just rename things as appropriate/usual.  Then delete the entire `script-output/FactorioMaps` directory in your factorio work directory, then post the log after another run?  :-)

**Comment by OvermindDL1** [comment] 2019-10-09 18:34
Hmm, interesting.  Did it generate a proper map or is it 'wrong' somehow when you view it in the browser?

**Comment by L0laapk3** [comment] 2019-10-09 18:39
log3 and log4 look like, while there is an error, the map should be fully generated correctly. Is this true?

**Comment by Luke-101** [comment] 2019-10-09 18:45
yes it's true
the files for the map works perfectly

**Comment by L0laapk3** [comment] 2019-10-13 20:40
Since its non critical and I cant manage to replicate it whatsoever, Im going to go ahead and close this ticket.

**Closed by L0laapk3** 2019-10-13 20:40 UTC
Labels: help wanted
